//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.MaDPractica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comenta
    {
        public decimal costumer_id { get; set; }
        public decimal product_id { get; set; }
        public decimal tag { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Costumer Costumer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tag Tag1 { get; set; }
    }
}
