//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.MaDPractica.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class practicaMaDEntities : DbContext
    {
        public practicaMaDEntities()
            : base("name=practicaMaDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Comenta> Comenta { get; set; }
        public virtual DbSet<Costumer> Costumer { get; set; }
        public virtual DbSet<Credit_card> Credit_card { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Producto_por_pedido> Producto_por_pedido { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
    }
}
