//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.MaDPractica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public decimal product_id { get; set; }
        public decimal property_id { get; set; }
        public string properties_value { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}
